name: DoubleA-HubMusic
main: com.andrew121410.mc.hubmusic.HubMusic
version: 1.0
api-version: 1.21

commands:
  hubmusic:

permissions:
  hubmusic.command:
    description: Allows to do hubmusic
    default: op