name: HubMusic
main: com.andrew121410.mc.hubmusic.Main
version: 1.0
api-version: 1.16

depend: [NoteBlockAPI]

commands:
  hubmusic:

permissions:
  hubmusic.command:
    description: Allows to do hubmusic
    default: op